# Generated by Django 6.0.5 on 2026-05-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horarios',
            field=models.ManyToManyField(related_name='agendamentos', to='agendamento.horario', verbose_name='Horários'),
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='horario',
        ),
    ]
