# Generated by Django 6.0.5 on 2026-05-19 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_agendamento_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='agendamento.semestre', verbose_name='Semestre'),
        ),
    ]
