# Generated by Django 6.0.5 on 2026-05-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_agendamento_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='solicitou_exclusao',
            field=models.BooleanField(default=False, verbose_name='Solicitou Exclusão'),
        ),
    ]
